# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy - AlaFein API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://alafein.azurecr.io/
        username: ${{ secrets.AzureAppService_API_ContainerUsername }}
        password: ${{ secrets.AzureAppService_API_ContainerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: alafein.azurecr.io/${{ secrets.AzureAppService_API_ContainerUsername }}/alafein-api:${{ github.sha }}
        file: ./DotNetBaseProject/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alafein'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_API_PublishProfile }}
        images: 'alafein.azurecr.io/${{ secrets.AzureAppService_API_ContainerUsername }}/alafein-api:${{ github.sha }}'